### ISSUE TITLE
CUDA_ERROR_UNKNOWN (999): unknown error | WORKAROUND

### ISSUE THREAD

**Issue by Franiac** [obsproject/obs-studio#11381]
### Operating System Info

Other

### Other OS

Linux Mint Debian Edition (Debian Bookworm)

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/Qvsf2B1DgEdqjFiO

### Expected Behavior

OBS should be capable of initializing CUDA itself.

### Current Behavior

OBS is not capable of initializing CUDA by itself, but it can be made working by jump-starting CUDA by another application like Davinci Resolve.

I always get an error after rebooting the PC if I start recording in OBS:

`
init_cuda_ctx: CUDA call "cu->cuInit(0)" failed with CUDA_ERROR_UNKNOWN (999): unknown error
`

Due to a coincidence I found out that whenever I run Davinci Resolce, which is also running and initializing CUDA, OBS also suddenly works!

So my guess is that Davinci Resolve initializes something OBS needs and makes it run perfectly fine. Even if you close Davinci Resolve and reopen OBS, it still works. OBS just stops working again when rebooting the system. Run Davinci Resolve again and OBS is fine again. I don't understand it, but I hope this helps tracing the issue, since it seems to be quite common on Linux systems across the board. Probably OBS (using NVENC) can be jump-started by any application successfully running CUDA (this is an assumption).

Log when OBS fails:

```
21:24:06.095: Using EGL/X11
21:24:06.095: CPU Name: AMD Ryzen 7 5800X3D 8-Core Processor
21:24:06.095: CPU Speed: 2200.000MHz
21:24:06.095: Physical Cores: 8, Logical Cores: 16
21:24:06.095: Physical Memory: 32003MB Total, 29833MB Free
21:24:06.095: Kernel Version: Linux 6.1.0-26-amd64
21:24:06.095: Flatpak Branch: stable
21:24:06.095: Flatpak Arch: x86_64
21:24:06.095: Flatpak Runtime: runtime/org.kde.Platform/x86_64/6.6
21:24:06.095: App Extensions:
21:24:06.095:  - com.obsproject.Studio.Locale
21:24:06.095: Runtime Extensions:
21:24:06.095:  - org.freedesktop.Platform.GL.default
21:24:06.095:  - org.freedesktop.Platform.GL.nvidia-560-35-03
21:24:06.095:  - org.freedesktop.Platform.openh264
21:24:06.095:  - org.gtk.Gtk3theme.Mint-Y-Dark-Aqua
21:24:06.095:  - org.kde.Platform.Locale
21:24:06.095:  - org.freedesktop.Platform.GL.default
21:24:06.095: Flatpak Framework Version: 1.14.10
21:24:06.095: Desktop Environment: X-Cinnamon (cinnamon)
21:24:06.095: Session Type: x11
21:24:06.095: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.21.1
21:24:06.096: Qt Version: 6.6.3 (runtime), 6.6.3 (compiled)
21:24:06.096: Portable mode: false
21:24:06.129: OBS 30.2.3 (linux)
21:24:06.129: ---------------------------------
21:24:06.134: ---------------------------------
21:24:06.134: audio settings reset:
21:24:06.134: 	samples per sec: 48000
21:24:06.134: 	speakers:        2
21:24:06.134: 	max buffering:   960 milliseconds
21:24:06.134: 	buffering type:  dynamically increasing
21:24:06.135: ---------------------------------
21:24:06.135: Initializing OpenGL...
21:24:06.239: Loading up OpenGL on adapter NVIDIA Corporation NVIDIA GeForce RTX 4070 SUPER/PCIe/SSE2
21:24:06.239: OpenGL loaded successfully, version 3.3.0 NVIDIA 560.35.03, shading language 3.30 NVIDIA via Cg compiler
21:24:06.261: ---------------------------------
21:24:06.261: video settings reset:
21:24:06.261: 	base resolution:   2560x1440
21:24:06.261: 	output resolution: 2560x1440
21:24:06.261: 	downscale filter:  Lanczos
21:24:06.261: 	fps:               60/1
21:24:06.261: 	format:            NV12
21:24:06.261: 	YUV mode:          Rec. 709/Partial
21:24:06.261: NV12 texture support enabled
21:24:06.261: P010 texture support not available
21:24:06.298: Audio monitoring device:
21:24:06.298: 	name: Default
21:24:06.298: 	id: default
21:24:06.298: ---------------------------------
21:24:06.312: No AJA devices found, skipping loading AJA UI plugin
21:24:06.312: Failed to initialize module 'aja-output-ui.so'
21:24:06.324: No AJA devices found, skipping loading AJA plugin
21:24:06.324: Failed to initialize module 'aja.so'
21:24:06.478: [pipewire] No capture sources available
21:24:06.503: v4l2loopback not installed, virtual camera not registered
21:24:06.510: [obs-browser]: Version 2.23.6
21:24:06.510: [obs-browser]: CEF Version 103.0.5060.134 (runtime), 103.0.0-5060-shared-textures.2594+g17f8588+chromium-103.0.5060.134 (compiled)
21:24:06.520: NVENC supported
21:24:06.520: VAAPI: Failed to initialize display in vaapi_device_h264_supported
21:24:06.520: FFmpeg VAAPI H264 encoding not supported
21:24:06.520: VAAPI: Failed to initialize display in vaapi_device_av1_supported
21:24:06.521: FFmpeg VAAPI AV1 encoding not supported
21:24:06.521: VAAPI: Failed to initialize display in vaapi_device_hevc_supported
21:24:06.521: FFmpeg VAAPI HEVC encoding not supported
21:24:06.582: [obs-websocket] [obs_module_load] you can haz websockets (Version: 5.5.2 | RPC Version: 1)
21:24:06.582: [obs-websocket] [obs_module_load] Qt version (compile-time): 6.6.3 | Qt version (run-time): 6.6.3
21:24:06.582: [obs-websocket] [obs_module_load] Linked ASIO Version: 103002
21:24:06.586: [obs-websocket] [obs_module_load] Module loaded.
21:24:06.605: ---------------------------------
21:24:06.605:   Loaded Modules:
21:24:06.605:     text-freetype2.so
21:24:06.605:     rtmp-services.so
21:24:06.605:     obs-x264.so
21:24:06.605:     obs-websocket.so
21:24:06.605:     obs-webrtc.so
21:24:06.605:     obs-vst.so
21:24:06.605:     obs-transitions.so
21:24:06.605:     obs-qsv11.so
21:24:06.605:     obs-outputs.so
21:24:06.605:     obs-libfdk.so
21:24:06.605:     obs-filters.so
21:24:06.605:     obs-ffmpeg.so
21:24:06.605:     obs-browser.so
21:24:06.605:     linux-v4l2.so
21:24:06.605:     linux-pulseaudio.so
21:24:06.605:     linux-pipewire.so
21:24:06.605:     linux-jack.so
21:24:06.605:     linux-capture.so
21:24:06.605:     image-source.so
21:24:06.605:     frontend-tools.so
21:24:06.605: ---------------------------------
21:24:06.606: ---------------------------------
21:24:06.606: Available Encoders:
21:24:06.606:   Video Encoders:
21:24:06.606: 	- ffmpeg_svt_av1 (SVT-AV1)
21:24:06.606: 	- ffmpeg_aom_av1 (AOM AV1)
21:24:06.606: 	- jim_nvenc (NVIDIA NVENC H.264)
21:24:06.606: 	- jim_hevc_nvenc (NVIDIA NVENC HEVC)
21:24:06.606: 	- jim_av1_nvenc (NVIDIA NVENC AV1)
21:24:06.606: 	- obs_x264 (x264)
21:24:06.606:   Audio Encoders:
21:24:06.606: 	- ffmpeg_aac (FFmpeg AAC)
21:24:06.606: 	- ffmpeg_opus (FFmpeg Opus)
21:24:06.606: 	- ffmpeg_pcm_s16le (FFmpeg PCM (16-bit))
21:24:06.606: 	- ffmpeg_pcm_s24le (FFmpeg PCM (24-bit))
21:24:06.606: 	- ffmpeg_pcm_f32le (FFmpeg PCM (32-bit float))
21:24:06.606: 	- ffmpeg_alac (FFmpeg ALAC (24-bit))
21:24:06.606: 	- ffmpeg_flac (FFmpeg FLAC (16-bit))
21:24:06.606: 	- libfdk_aac (libfdk AAC)
21:24:06.606: ==== Startup complete ===============================================
21:24:06.646: All scene data cleared
21:24:06.646: ------------------------------------------------
21:24:06.650: pulse-input: Server name: 'PulseAudio (on PipeWire 0.3.65) 15.0.0'
21:24:06.650: pulse-input: Audio format: s16le, 48000 Hz, 2 channels
21:24:06.650: pulse-input: Started recording from 'alsa_output.usb-ARTURIA_MiniFuse_1_8830400623040646-00.HiFi__minifuse12_stereo_out_M1_0_0_1__sink.monitor'
21:24:06.650: [Loaded global audio device]: 'Desktop Audio'
21:24:06.651: xshm-input: Geometry 2560x1440 @ 0,0
21:24:06.652: Switched to scene 'Desktop'
21:24:06.652: ------------------------------------------------
21:24:06.652: Loaded scenes:
21:24:06.652: - scene 'Desktop':
21:24:06.652:     - source: 'Display Capture (XSHM)' (xshm_input)
21:24:06.652: ------------------------------------------------
21:24:07.222: adding 21 milliseconds of audio buffering, total audio buffering is now 21 milliseconds (source: Desktop Audio)
21:24:07.222: 
21:24:08.269: [obs-nvenc: 'advanced_video_recording'] init_cuda_ctx: CUDA call "cu->cuInit(0)" failed with CUDA_ERROR_UNKNOWN (999): unknown error
21:24:08.271: [obs-nvenc: 'advanced_video_recording'] init_cuda_ctx: CUDA call "cu->cuInit(0)" failed with CUDA_ERROR_UNKNOWN (999): unknown error
21:24:08.271: Already in fallback encoder, can't fall back further!
```

Log when OBS works after Davinci Resolve was ran:

```
21:24:56.471: Using EGL/X11
21:24:56.472: CPU Name: AMD Ryzen 7 5800X3D 8-Core Processor
21:24:56.472: CPU Speed: 3552.433MHz
21:24:56.472: Physical Cores: 8, Logical Cores: 16
21:24:56.472: Physical Memory: 32003MB Total, 29209MB Free
21:24:56.472: Kernel Version: Linux 6.1.0-26-amd64
21:24:56.472: Flatpak Branch: stable
21:24:56.472: Flatpak Arch: x86_64
21:24:56.472: Flatpak Runtime: runtime/org.kde.Platform/x86_64/6.6
21:24:56.472: App Extensions:
21:24:56.472:  - com.obsproject.Studio.Locale
21:24:56.472: Runtime Extensions:
21:24:56.472:  - org.freedesktop.Platform.GL.default
21:24:56.472:  - org.freedesktop.Platform.GL.nvidia-560-35-03
21:24:56.472:  - org.freedesktop.Platform.openh264
21:24:56.472:  - org.gtk.Gtk3theme.Mint-Y-Dark-Aqua
21:24:56.472:  - org.kde.Platform.Locale
21:24:56.472:  - org.freedesktop.Platform.GL.default
21:24:56.472: Flatpak Framework Version: 1.14.10
21:24:56.472: Desktop Environment: X-Cinnamon (cinnamon)
21:24:56.472: Session Type: x11
21:24:56.472: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.21.1
21:24:56.473: Qt Version: 6.6.3 (runtime), 6.6.3 (compiled)
21:24:56.473: Portable mode: false
21:24:56.495: OBS 30.2.3 (linux)
21:24:56.495: ---------------------------------
21:24:56.500: ---------------------------------
21:24:56.500: audio settings reset:
21:24:56.500: 	samples per sec: 48000
21:24:56.500: 	speakers:        2
21:24:56.500: 	max buffering:   960 milliseconds
21:24:56.500: 	buffering type:  dynamically increasing
21:24:56.500: ---------------------------------
21:24:56.500: Initializing OpenGL...
21:24:56.578: Loading up OpenGL on adapter NVIDIA Corporation NVIDIA GeForce RTX 4070 SUPER/PCIe/SSE2
21:24:56.578: OpenGL loaded successfully, version 3.3.0 NVIDIA 560.35.03, shading language 3.30 NVIDIA via Cg compiler
21:24:56.597: ---------------------------------
21:24:56.597: video settings reset:
21:24:56.597: 	base resolution:   2560x1440
21:24:56.597: 	output resolution: 2560x1440
21:24:56.597: 	downscale filter:  Lanczos
21:24:56.597: 	fps:               60/1
21:24:56.597: 	format:            NV12
21:24:56.597: 	YUV mode:          Rec. 709/Partial
21:24:56.597: NV12 texture support enabled
21:24:56.597: P010 texture support not available
21:24:56.597: Audio monitoring device:
21:24:56.597: 	name: Default
21:24:56.597: 	id: default
21:24:56.597: ---------------------------------
21:24:56.608: No AJA devices found, skipping loading AJA UI plugin
21:24:56.608: Failed to initialize module 'aja-output-ui.so'
21:24:56.618: No AJA devices found, skipping loading AJA plugin
21:24:56.618: Failed to initialize module 'aja.so'
21:24:56.744: [pipewire] No capture sources available
21:24:56.764: v4l2loopback not installed, virtual camera not registered
21:24:56.771: [obs-browser]: Version 2.23.6
21:24:56.771: [obs-browser]: CEF Version 103.0.5060.134 (runtime), 103.0.0-5060-shared-textures.2594+g17f8588+chromium-103.0.5060.134 (compiled)
21:24:56.778: NVENC supported
21:24:56.778: VAAPI: Failed to initialize display in vaapi_device_h264_supported
21:24:56.778: FFmpeg VAAPI H264 encoding not supported
21:24:56.778: VAAPI: Failed to initialize display in vaapi_device_av1_supported
21:24:56.778: FFmpeg VAAPI AV1 encoding not supported
21:24:56.778: VAAPI: Failed to initialize display in vaapi_device_hevc_supported
21:24:56.779: FFmpeg VAAPI HEVC encoding not supported
21:24:56.833: [obs-websocket] [obs_module_load] you can haz websockets (Version: 5.5.2 | RPC Version: 1)
21:24:56.833: [obs-websocket] [obs_module_load] Qt version (compile-time): 6.6.3 | Qt version (run-time): 6.6.3
21:24:56.833: [obs-websocket] [obs_module_load] Linked ASIO Version: 103002
21:24:56.836: [obs-websocket] [obs_module_load] Module loaded.
21:24:56.855: ---------------------------------
21:24:56.855:   Loaded Modules:
21:24:56.855:     text-freetype2.so
21:24:56.855:     rtmp-services.so
21:24:56.855:     obs-x264.so
21:24:56.855:     obs-websocket.so
21:24:56.855:     obs-webrtc.so
21:24:56.855:     obs-vst.so
21:24:56.855:     obs-transitions.so
21:24:56.855:     obs-qsv11.so
21:24:56.855:     obs-outputs.so
21:24:56.855:     obs-libfdk.so
21:24:56.855:     obs-filters.so
21:24:56.855:     obs-ffmpeg.so
21:24:56.855:     obs-browser.so
21:24:56.855:     linux-v4l2.so
21:24:56.855:     linux-pulseaudio.so
21:24:56.855:     linux-pipewire.so
21:24:56.855:     linux-jack.so
21:24:56.855:     linux-capture.so
21:24:56.855:     image-source.so
21:24:56.855:     frontend-tools.so
21:24:56.855: ---------------------------------
21:24:56.855: ---------------------------------
21:24:56.855: Available Encoders:
21:24:56.855:   Video Encoders:
21:24:56.855: 	- ffmpeg_svt_av1 (SVT-AV1)
21:24:56.855: 	- ffmpeg_aom_av1 (AOM AV1)
21:24:56.855: 	- jim_nvenc (NVIDIA NVENC H.264)
21:24:56.855: 	- jim_hevc_nvenc (NVIDIA NVENC HEVC)
21:24:56.855: 	- jim_av1_nvenc (NVIDIA NVENC AV1)
21:24:56.855: 	- obs_x264 (x264)
21:24:56.855:   Audio Encoders:
21:24:56.855: 	- ffmpeg_aac (FFmpeg AAC)
21:24:56.855: 	- ffmpeg_opus (FFmpeg Opus)
21:24:56.855: 	- ffmpeg_pcm_s16le (FFmpeg PCM (16-bit))
21:24:56.855: 	- ffmpeg_pcm_s24le (FFmpeg PCM (24-bit))
21:24:56.855: 	- ffmpeg_pcm_f32le (FFmpeg PCM (32-bit float))
21:24:56.855: 	- ffmpeg_alac (FFmpeg ALAC (24-bit))
21:24:56.855: 	- ffmpeg_flac (FFmpeg FLAC (16-bit))
21:24:56.855: 	- libfdk_aac (libfdk AAC)
21:24:56.855: ==== Startup complete ===============================================
21:24:56.884: All scene data cleared
21:24:56.884: ------------------------------------------------
21:24:56.887: pulse-input: Server name: 'PulseAudio (on PipeWire 0.3.65) 15.0.0'
21:24:56.887: pulse-input: Audio format: s16le, 48000 Hz, 2 channels
21:24:56.887: pulse-input: Started recording from 'alsa_output.usb-ARTURIA_MiniFuse_1_8830400623040646-00.HiFi__minifuse12_stereo_out_M1_0_0_1__sink.monitor'
21:24:56.887: [Loaded global audio device]: 'Desktop Audio'
21:24:56.887: xshm-input: Geometry 2560x1440 @ 0,0
21:24:56.888: Switched to scene 'Desktop'
21:24:56.888: ------------------------------------------------
21:24:56.888: Loaded scenes:
21:24:56.888: - scene 'Desktop':
21:24:56.888:     - source: 'Display Capture (XSHM)' (xshm_input)
21:24:56.888: ------------------------------------------------
21:24:57.417: adding 21 milliseconds of audio buffering, total audio buffering is now 21 milliseconds (source: Desktop Audio)
21:24:57.417: 
21:24:58.713: [obs-nvenc: 'advanced_video_recording'] settings:
21:24:58.713: 	codec:        AV1
21:24:58.713: 	rate_control: CBR
21:24:58.713: 	bitrate:      10000
21:24:58.713: 	cqp:          20
21:24:58.713: 	keyint:       120
21:24:58.713: 	preset:       p7
21:24:58.713: 	tuning:       hq
21:24:58.713: 	multipass:    qres
21:24:58.713: 	profile:      main
21:24:58.713: 	width:        2560
21:24:58.713: 	height:       1440
21:24:58.713: 	b-frames:     2
21:24:58.713: 	lookahead:    false
21:24:58.713: 	psycho_aq:    true
21:24:58.713: 
21:24:58.757: ---------------------------------
21:24:58.757: [FFmpeg pcm_s24le encoder: 'Track1'] bitrate: 0, channels: 2, channel_layout: stereo
21:24:58.757: 
21:24:58.759: ==== Recording Start ===============================================
21:24:58.759: [ffmpeg muxer: 'adv_file_output'] Writing file '/home/franiac/2024-10-10_21-24-58.mkv'...
21:25:03.419: [ffmpeg muxer: 'adv_file_output'] Output of file '/home/franiac/2024-10-10_21-24-58.mkv' stopped
21:25:03.419: Output 'adv_file_output': stopping
21:25:03.419: Output 'adv_file_output': Total frames output: 267
21:25:03.419: Output 'adv_file_output': Total drawn frames: 280
21:25:03.419: ==== Recording Stop ================================================
```

### Steps to Reproduce

1. Install OBS Studio 30.2.3 from official Flatpak Repo
2. Run it and select an NVENC encoder for recording
3. Click "Start Recording"
4. CUDA initialization error occures
5. Close OBS
6. Run Davinci Resolve
7. Close Davinci Resolve
8. Run OBS again
9. Click "Start Recording" again
10. WORKS!

**Comment by kkartaltepe** [comment]
You'll have to configure your system correctly for cuda if you want to use flatpak.

**Comment by Franiac** [comment]
Can you elaborate on that or at least link a guide?

> You'll have to configure your system correctly

That's an oddly unspecific instruction and is not very helpful. You seem to know things so please share some of it?

And no comment on why Davinci Resolve makes OBS suddenly work without any further intervention?

**Comment by derrod** [comment]
There seem to be various issues with CUDA in containers such as Flatpak depending on your system configuration.

Some people claim changing certain power management related options of the nvidia driver fixes it, e.g. https://github.com/tensorflow/tensorflow/issues/53341#issuecomment-1166532019 or https://forums.developer.nvidia.com/t/cannot-get-cuda-to-work-on-opensuse-tumbleweed-slowroll/297329/6.

Seems running an application outside a container (e.g. Resolve in this case) can jumpster it. But this isn't something we can fix but an NVIDIA driver issue.

**Comment by Franiac** [comment]
Thank you for the links. After fiddling around for another couple minutes I figured it out. For the sake of helping others who stumble on this issue, here's what I've learned:

Not only does Davinci Resolve jump-start CUDA in Flatpak, but also a simple call of `sudo nvidia-smi` in the terminal does. After figuring that out I tried to understand, what actually changes due to the command and I found the 2 missing parts:

Here's `lsmod | grep nvidia` before running `nvidia-smi`:

```
nvidia_drm            102400  5
nvidia_modeset       1544192  7 nvidia_drm
nvidia               9670656  74 nvidia_modeset
video                  65536  3 asus_wmi,nouveau,nvidia_modeset
drm_kms_helper        212992  3 drm_display_helper,nvidia_drm,nouveau
drm                   614400  13 drm_kms_helper,drm_display_helper,nvidia,drm_ttm_helper,nvidia_drm,ttm,nouveau
```

And here's after:

```
nvidia_uvm           4702208  0
nvidia_drm            102400  5
nvidia_modeset       1544192  7 nvidia_drm
nvidia               9670656  75 nvidia_uvm,nvidia_modeset
video                  65536  3 asus_wmi,nouveau,nvidia_modeset
drm_kms_helper        212992  3 drm_display_helper,nvidia_drm,nouveau
drm                   614400  13 drm_kms_helper,drm_display_helper,nvidia,drm_ttm_helper,nvidia_drm,ttm,nouveau
```

And also `ls -l | grep nvidia` in directory `/dev/` before:

```
crw-rw-rw-   1 root root    195,     0 Oct 11 01:07 nvidia0
crw-rw-rw-   1 root root    195,   255 Oct 11 01:07 nvidiactl
crw-rw-rw-   1 root root    195,   254 Oct 11 01:07 nvidia-modeset
```

And after:

```
crw-rw-rw-   1 root root    195,     0 Oct 11 01:07 nvidia0
drwxr-xr-x   2 root root            80 Oct 11 01:09 nvidia-caps
crw-rw-rw-   1 root root    195,   255 Oct 11 01:07 nvidiactl
crw-rw-rw-   1 root root    195,   254 Oct 11 01:07 nvidia-modeset
crw-rw-rw-   1 root root    234,     0 Oct 11 01:09 nvidia-uvm
crw-rw-rw-   1 root root    234,     1 Oct 11 01:09 nvidia-uvm-tools
```

So it's pretty clear what's happening. The kernel module `nvidia_uvm` and the associated device node are not loaded after a reboot or coming back from hibernation.

The first issue is simply solved by running `modprobe nvidia_uvm`.

The second issue can be tackled by getting the device ID of `nvidia-uvm` with `grep nvidia-uvm /proc/devices | awk '{print $1}'` and creating a device node with `mknod -m 666 /dev/nvidia-uvm c [device ID from previous command] 0`.

After that, OBS can be started and NVENC works perfectly. Hope that helps.

**Comment by Franiac** [comment]
And some additional info on how to automate all that at startup:

1. Create a file `/lib/systemd/system/nvidia-smi.service` with the following content:

```
[Unit]
Description=Run nvidia-smi
After=systemd-modules-load.service
Requires=systemd-modules-load.service

[Service]
Type=oneshot
ExecStart=/usr/bin/nvidia-smi

[Install]
WantedBy=multi-user.target
```

2. Run `sudo systemctl daemon-reload`
3. Run `sudo systemctl enable nvidia-smi.service`
4. Reboot your system

Now every Flatpak application is able to run CUDA without any manual intervention, not only OBS.

**Comment by Tr0gdorTheBurninator** [comment]
@Franiac you are a lifesaver. I was banging my head against a wall trying to figure out why OBS wouldn't run. Much appreciated!!
